version: '3'

services:
  poketeam:
    container_name: poketeam
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENV_NAME: ${ENV_NAME}
    env_file: .env
    volumes:
      -  './src/:/home/src'
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db

  poketeam-test:
    container_name: poketeam-test
    build:  
      context: .
      dockerfile: docker/Dockerfile
      args:
        ENV_NAME: test
    env_file: test.env
    volumes:
      -  './src/:/home/src'
    command: >
      bash -c "pytest -vv --cov-report term-missing --cov"

  db:
    image: postgres:13.2-alpine
    container_name: db
    env_file: .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT}:${DB_PORT}

networks:
  default:
    name: triagil-network
    external: True
